# Generated by Django 3.0.5 on 2020-06-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAPId', models.CharField(max_length=30)),
                ('HOSTNAME', models.CharField(max_length=20)),
                ('LoopBack', models.CharField(max_length=20)),
                ('MacAddress', models.CharField(max_length=20)),
            ],
        ),
    ]
